<a href="https://colab.research.google.com/github/sravanmalla123/Data-Cleaning-Preprocessing/blob/main/Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Movie Recommendation System

This project aims to build a movie recommendation system using machine learning. Here are the planned steps:

1.  **Data Loading and Exploration**: Load a movie dataset and perform initial exploratory data analysis.
2.  **Data Preprocessing**: Clean and preprocess the data (e.g., handle missing values, text processing for movie titles/genres).
3.  **Feature Engineering**: Create features suitable for recommendation (e.g., TF-IDF for text, genre vectors).
4.  **Model Selection**: Choose and implement a recommendation algorithm (e.g., content-based filtering, collaborative filtering, or a hybrid approach).
5.  **Model Training and Evaluation**: Train the model and evaluate its performance using appropriate metrics.
6.  **Deployment (Streamlit)**: (Optional) Build a simple web application using Streamlit to interact with the recommendation system.

### Data Preprocessing

First, we'll extract the release year from the movie titles and clean the title field. Then, we'll process the genres.

In [2]:
# Extract year from title and clean title
movies_df['year'] = movies_df['title'].str.extract(r'\((\d{4})\)')
movies_df['title'] = movies_df['title'].str.replace(r'\s*\(\d{4}\)\s*', '', regex=True).str.strip()

print('\n--- Movies DataFrame after extracting year and cleaning title ---')
display(movies_df.head())

--- Movies DataFrame after extracting year and cleaning title ---

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [3]:
# Split genres into a list and handle potential empty genres
movies_df['genres'] = movies_df['genres'].apply(lambda x: x.split('|') if isinstance(x, str) else [])

print('\n--- Movies DataFrame after splitting genres ---')
display(movies_df.head())

--- Movies DataFrame after splitting genres ---

,movieId,title,genres,year
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995
2,3,Grumpier Old Men,"[Comedy, Romance]",1995
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995
4,5,Father of the Bride Part II,[Comedy],1995

In [4]:
import pandas as pd

# --- Data Loading ---
# For this example, let's assume you have a 'movies.csv' file.
# You might need to download a dataset like MovieLens (e.g., ml-latest-small) if you don't have one.
# Replace 'movies.csv' with the actual path to your movie dataset.
# Example: movies_df = pd.read_csv('path/to/your/movies.csv')

# Placeholder for demonstration. If you have a CSV, uncomment and modify the line above.
# If you don't have a CSV, you can create a dummy DataFrame or download one.

# Dummy DataFrame for initial demonstration if no file is available
data = {
    'movieId': [1, 2, 3, 4, 5],
    'title': ['Toy Story (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)', 'Waiting to Exhale (1995)', 'Father of the Bride Part II (1995)'],
    'genres': ['Adventure|Animation|Children|Comedy|Fantasy', 'Adventure|Children|Fantasy', 'Comedy|Romance', 'Comedy|Drama|Romance', 'Comedy']
}
movies_df = pd.DataFrame(data)


print('--- Dataset Info ---')
movies_df.info()

print('\n--- First 5 Rows ---')
display(movies_df.head())

--- Dataset Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  5 non-null      int64
 1   title    5 non-null      object
 2   genres   5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

--- First 5 Rows ---

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy